spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog_app?sslmode=disable
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

server:
  port: 9001
  tomcat:
    connection-timeout: 15s
    keep-alive-timeout: 30s
    threads:
      max: 50
      min-spare: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
app:
  greeting: Default message

